package ryanhurst.weather

/**
 * Created by ryan on 1/9/17.
 */

private val KIMBALL_JUNCTION = "KIJ"
private val MUN_GOLF_COURSE = "SNC"

private val CANYONS_LOOKOUT = "CLK"
private val CANYONS_CONDOR = "CCD"
private val CANYONS_9990 = "C99"
private val CANYONS_DAYBREAK = "CDYBK"
private val CANYONS_DREAMSCAPE = "CDSUT"

private val PARK_CITY_SUMMIT = "PCT"
private val PARK_CITY_BONANZ = "PCZ"
private val PARK_CITY_JUPITER = "PKC"
private val PARK_CITY_CRESCENT = "PCR"
private val PARK_CITY_EAGLE = "PCS"
private val PARK_CITY_PINECONE = "PCPCN"

val STATIONS_ARRAY = arrayOf(MUN_GOLF_COURSE, KIMBALL_JUNCTION, CANYONS_LOOKOUT, CANYONS_CONDOR, CANYONS_9990, CANYONS_DAYBREAK, CANYONS_DREAMSCAPE, PARK_CITY_SUMMIT, PARK_CITY_JUPITER, PARK_CITY_CRESCENT, PARK_CITY_EAGLE, PARK_CITY_PINECONE)
val SHORT_STATIONS_ARRAY = arrayOf(CANYONS_9990, PARK_CITY_JUPITER)